<?php
/** @var \Dotdigitalgroup\Email\Block\Adminhtml\EngagementCloudTrialInterface $block */
// phpcs:disable Magento2.Legacy.EscapeMethodsOnBlockClass
?>
<script type="text/x-magento-init">
    {
        "*": {
            "Dotdigitalgroup_Email/js/engagementCloudEmbed": {
                "iframeSrc": "<?= $block->escapeHtml($block->getAction()) ?>"
            },
            "Dotdigitalgroup_Email/js/engagementCloudTrial": {
                "callback": "<?= $block->escapeHtml($block->getLocalCallbackUrl()) ?>",
                "micrositeUrl": "<?= $block->escapeHtml($block->getTrialSignupHostAndScheme()) ?>"
            }
        }
    }
</script>
<?php // phpcs:enable ?>
