<?php /** @var \Dotdigitalgroup\Email\Block\Adminhtml\EngagementCloudTrialInterface $block */?>
<script type="text/x-magento-init">
    {
        "*": {
            "Dotdigitalgroup_Email/js/engagementCloudEmbed": {
                "iframeSrc": "<?= $block->escapeUrl($block->getAction()) ?>"
            },
            "Dotdigitalgroup_Email/js/engagementCloudTrial": {
                "callback": "<?= $block->escapeUrl($block->getLocalCallbackUrl()) ?>",
                "micrositeUrl": "<?= $block->escapeUrl($block->getTrialSignupHostAndScheme()) ?>"
            }
        }
    }
</script>
