<ul class="messages">
    <li class="notice-msgw">
        <table>
            <tr>
                <th>
                    <strong><?php echo __('API valid')?>:</strong>
                </th>
                <td><?php echo $block->escapeHtml($this->getApiValid()) ?></td>
            </tr>
            <tr>
                <th>
                    <strong><?php echo __('Cron last execution')?>:</strong>
                </th>
                <td><?php echo $block->getCronLastExecution(); ?></td>
            </tr>
            <tr>
                <th>
                    <strong><?php echo __('Dynamic content passcode')?>:</strong>
                </th>
                <td><?php echo $block->getDynamicContentPasscode()?></td>
            </tr>
            <tr>
                <th>
                    <strong><?php echo __('Abandoned Cart limit time')?>:</strong>
                </th>
                <td><?php echo $block->getAbandonedCartLimit()?></td>
            </tr>
        </table>
    </li>
</ul>
