<ul class="messages">
    <li class="notice-msgw">
        <table>
            <tr>
                <th>
                    <strong><?php echo __('PHP Version')?>:</strong>
                </th>
                <td><?php echo $block->escapeHtml($this->getPhpVersion()) ?></td>
            </tr>
            <tr>
                <th>
                    <strong><?php echo __('PHP max execution time')?>:</strong>
                </th>
                <td><?php echo $block->getPhpMaxExecutionTime(); ?></td>
            </tr>
            <tr>
                <th>
                    <strong><?php echo __('Mode ')?>:</strong>
                </th>
                <td><?php echo $block->getDeveloperMode()?></td>
            </tr>
            <tr>
                <th>
                    <strong><?php echo __('Magento Version ')?>:</strong>
                </th>
                <td><?php echo $block->getMagentoVersion()  .  '  ' . $block->getMagentoEdition()?></td>
            </tr>
            <tr>
                <th>
                    <strong><?php echo __('Connector Version ')?>:</strong>
                </th>
                <td><?php echo $block->getConnectorVersion()?></td>
            </tr>
            
        </table>
    </li>
</ul>
