<?php
/** @var \Dotdigitalgroup\Email\Block\Feefo $block */
// @codingStandardsIgnoreFile
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns="http://www.w3.org/1999/html">

<?php $reviews = $block->getProductsReview(); ?>
    <head>
        <title><?= $block->escapeHtml(__("Feefo Feedback")); ?></title>
        <link rel="stylesheet" type="text/css" media="all"
              href="<?= $block->escapeUrl($block->getCssUrl()); ?>" />
    </head>
    <body>
        <table class="main-table">
            <tbody>
                <?php foreach ($reviews as $name => $review) : ?>
                    <tr>
                        <td>
                            <?= $block->escapeHtml($review); ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </body>
</html>