<?php $reviews = $this->getProductsReview(); ?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns="http://www.w3.org/1999/html">
    <head>
        <title><?php echo $this->__("Feefo Feedback"); ?></title>
    </head>
    <body>
        <table class="main-table">
            <tbody>
                <?php foreach($reviews as $name => $review): ?>
                    <tr>
                        <td style="border-bottom: 2px #d3d3d3 dotted; padding-top: 5px; padding-bottom: 5px">
                            <?php echo $this->escapeHtml($review); ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </body>
</html>
<style>
    .comm-table td{
        padding-bottom: 5px;
    }
    .comm-table th{
        text-align: left;
        border-bottom: 1px black solid;
        padding-bottom: 3px;
    }
</style>