<?php
/** @var \Dotdigitalgroup\Email\Block\Feefo $block */
// phpcs:disable Magento2.Legacy.EscapeMethodsOnBlockClass

$data = $block->getServiceScoreLogo();
$vendorUrl = $data['vendorUrl'];
$fullUrl = $data['fullUrl'];
?>
<a href="<?= $block->escapeUrl($vendorUrl)?>" target='_blank'>
    <img alt='Feefo logo' border='0' src="<?= $block->escapeUrl($fullUrl)?>"
         title="<?= $block->escapeHtml(__('See what our customers say about us')); ?>"
    >
</a>
<?php // phpcs:enable ?>
