<?php
$i = 0;
$mode = $this->getMode();
$products = $this->getLoadedProductCollection();
?>

<?php if (!empty($products)): ?>
    <?php
    $dynamicStyle = $this->helper->getDynamicStyles();
    ?>
    <style>
        .product-name{
            color: <?php echo $dynamicStyle['nameColor'];?>;
            font-size: <?php echo $dynamicStyle['fontSize'];?>;
        <?php if(in_array('bold', $dynamicStyle['nameStyle'])): ?>
            font-weight: bold;
        <?php endif; ?>
        <?php if(in_array('italic', $dynamicStyle['nameStyle'])): ?>
            font-style: italic;
        <?php endif; ?>
        <?php if(in_array('underline', $dynamicStyle['nameStyle'])): ?>
            text-decoration: underline;
        <?php endif; ?>
        }
        .product-price{
            color: <?php echo $dynamicStyle['priceColor'];?>;
            font-size: <?php echo $dynamicStyle['priceFontSize'];?>;
        <?php if(in_array('bold', $dynamicStyle['priceStyle'])): ?>
            font-weight: bold;
        <?php endif; ?>
        <?php if(in_array('italic', $dynamicStyle['priceStyle'])): ?>
            font-style: italic;
        <?php endif; ?>
        <?php if(in_array('underline', $dynamicStyle['priceStyle'])): ?>
            text-decoration: underline;
        <?php endif; ?>
        }
        .proudct-url{
            color: <?php echo $dynamicStyle['urlColor'];?>;
            font-size: <?php echo $dynamicStyle['urlFontSize'];?>;
        <?php if(in_array('bold', $dynamicStyle['linkStyle'])): ?>
            font-weight: bold;
        <?php endif; ?>
        <?php if(in_array('italic', $dynamicStyle['linkStyle'])): ?>
            font-style: italic;
        <?php endif; ?>
        <?php if(in_array('underline', $dynamicStyle['linkStyle'])): ?>
            text-decoration: underline;
        <?php endif; ?>
        }
        .other-text{
            color: <?php echo $dynamicStyle['otherColor'];?>;
            font-size: <?php echo $dynamicStyle['otherFontSize'];?>;
        <?php if(in_array('bold', $dynamicStyle['otherStyle'])): ?>
            font-weight: bold;
        <?php endif; ?>
        <?php if(in_array('italic', $dynamicStyle['otherStyle'])): ?>
            font-style: italic;
        <?php endif; ?>
        <?php if(in_array('underline', $dynamicStyle['otherStyle'])): ?>
            text-decoration: underline;
        <?php endif; ?>
        }
        .product-table{
            font-family: <?php echo $dynamicStyle['docFont'];?>;
            background-color: <?php echo $dynamicStyle['docBackgroundColor'];?>;
            width: 100% !important;
        }
        .product-table img{
            display: block;
            margin-left: auto;
            margin-right: auto
        }
        .product-table td{
            width: 25%;
            padding-bottom: 10px;
        }
        /** Styling from config field **/
        <?php echo $dynamicStyle['dynamicStyling'];?>
        /** Responsive  **/
        @media (max-width: 760px) {
            /* Force table to not be like tables anymore */
            table, thead, tbody, th, td, tr {
                display: block;
            }
            .product-table td{
                width: 172px !important;
            }
            .product-table {
                width: auto !important;
            }
        }
    </style>
<?php endif; ?>

<?php foreach ($products as $key => $_product) :?>
    <?php  if($i == 0):?>
        <table class="product-table" border="0" width="147" cellpadding="0" cellspacing="0" style='border-collapse: collapse; font-size:12';><tr>
    <?php endif;?>
    <?php if($mode == 'list'):?>
        </tr><tr>
    <?php endif;?>

    <td style="vertical-align: text-top; padding-right: 2px;">
        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"
           class="product-image"><?php echo $block->getImage($_product, 'category_page_grid')->toHtml();?>
            </a>
        <div class="product-name" align="center"><b><?php echo $this->escapeHtml(substr($_product->getName(), 0, 40));?></b></div>
        <div class="product-price" align="center">
            <?php echo $this->getLayout()->getBlock('ddg.product.price.render.default')->render('final_price', $_product, array());?>
        </div>
        <div align="center">
            <a class="proudct-url" href="<?php echo $_product->getProductUrl();?>">
                <?php
                if ($urlText = $this->getTextForUrl($_product->getStoreId()))
                    echo $this->escapeHtml($urlText);
                else
                    echo __('View Now');
                ?>
            </a>
        </div>
    </td>

    <?php if($i++ % 4 ==3 && $mode == 'grid'):?></tr><tr><?php endif;?>
<?php endforeach;?>
<?php if( $i > 0):?> </table>
<?php endif;

