<?php
/**
 * @var \Dotdigitalgroup\Email\Block\Recommended\Mostviewed $block
 * @var \Magento\Framework\Escaper $escaper
 */
?>
<?php
    $i = 0;
    $mode = $block->getMode();
    $products = $block->getLoadedProductCollection();
?>
<?php if ($products): ?>
    <?php $dynamicStyle = $block->getDynamicStyles(); ?>
    <style>
        .product-name{
            color: <?= $escaper->escapeHtml($dynamicStyle['nameColor']); ?>;
            font-size: <?= $escaper->escapeHtml($dynamicStyle['fontSize']); ?>;
        <?php if (in_array('bold', $dynamicStyle['nameStyle'])): ?>
            font-weight: bold;
        <?php endif; ?><?php if (in_array('italic', $dynamicStyle['nameStyle'])): ?>
            font-style: italic;
        <?php endif; ?><?php if (in_array('underline', $dynamicStyle['nameStyle'])): ?>
            text-decoration: underline;
        <?php endif; ?>
        }
        .product-price{
            color: <?= $escaper->escapeHtml($dynamicStyle['priceColor']);?>;
            font-size: <?= $escaper->escapeHtml($dynamicStyle['priceFontSize']);?>;
        <?php if (in_array('bold', $dynamicStyle['priceStyle'])): ?>
            font-weight: bold;
        <?php endif; ?><?php if (in_array('italic', $dynamicStyle['priceStyle'])): ?>
            font-style: italic;
        <?php endif; ?><?php if (in_array('underline', $dynamicStyle['priceStyle'])): ?>
            text-decoration: underline;
        <?php endif; ?>
        }
        .product-url{
            color: <?= $escaper->escapeHtml($dynamicStyle['urlColor']); ?>;
            font-size: <?= $escaper->escapeHtml($dynamicStyle['urlFontSize']); ?>;
        <?php if (in_array('bold', $dynamicStyle['linkStyle'])): ?>
            font-weight: bold;
        <?php endif; ?><?php if (in_array('italic', $dynamicStyle['linkStyle'])): ?>
            font-style: italic;
        <?php endif; ?><?php if (in_array('underline', $dynamicStyle['linkStyle'])): ?>
            text-decoration: underline;
        <?php endif; ?>
        }
        .product-table{
            font-family: <?= /* @noEscape */ $dynamicStyle['docFont']; ?>;
            background-color: <?= $escaper->escapeHtml($dynamicStyle['docBackgroundColor']); ?>;
            width: 100% !important;
        }
        .product-table img{
            display: block;
            margin-left: auto;
            margin-right: auto
        }
        .product-table td{
            width: 25%;
            padding-bottom: 10px;
        }
        /** Styling from config field **/
        <?= $escaper->escapeHtml($dynamicStyle['dynamicStyling']); ?>
        /** Responsive  **/
        @media (max-width: 760px) {
            /* Force table to not be like tables anymore */
            table, thead, tbody, th, td, tr {
                display: block;
            }
            .product-table td{
                width: 172px !important;
            }
            .product-table {
                width: auto !important;
            }
        }
    </style>
    <?php foreach ($products as $key => $_product): ?>
        <?php $productUrl = $block->getConfigurableParentUrl($_product); ?>
        <?php if ($i == 0): ?>
            <table class="product-table" border="0" width="147" cellpadding="0" cellspacing="0"
            style='border-collapse: collapse; font-size:12px';><tr>
        <?php endif; ?>
        <?php if ($mode == 'list'): ?>
            </tr><tr>
        <?php endif;?>

        <td style="vertical-align: text-top; padding-right: 2px;">
            <a href="<?= $escaper->escapeHtml($productUrl); ?>" title="<?= $escaper->escapeHtml(
                $block->stripTags(
                    $block->getImageLabel(
                        $_product,
                        'small_image'
                    ),
                    null,
                    true
                )
                     ); // @codingStandardsIgnoreLine ?>" class="product-image">
                <img src="<?= /* @noEscape */ $block->getProductImageUrl($_product, 'product_small_image') ?>"
                     alt="<?= $escaper->escapeHtml($_product->getName()) ?>">
            </a>
            <div class="product-name" align="center"><b><?= $escaper->escapeHtml(
                mb_substr($_product->getName(), 0, 40)
                    ); // @codingStandardsIgnoreLine ?></b></div>
            <div class="product-price" align="center">
                <?php $productPriceHtml = $block->getLayout()->getBlock('ddg.product.price.render.default')
                    ->render('final_price', $_product, []) ?>
                <?= /* @noEscape */ $productPriceHtml; ?>
            </div>
            <div align="center">
                <a class="product-url" href="<?= $escaper->escapeHtml($productUrl); ?>">
                    <?php if ($urlText = $block->getTextForUrl($_product->getStoreId())): ?>
                        <?= $escaper->escapeHtml($urlText); ?>
                    <?php else: ?>
                        <?= $escaper->escapehtml(__('View Now')); ?>
                    <?php endif;?>
                </a>
            </div>
        </td>

        <?php if ($i++ % 4 == 3 && $mode == 'grid'): ?>
            </tr><tr>
        <?php endif;?>
    <?php endforeach; ?>
    <?php if ($i > 0): ?>
        </table>
    <?php endif; ?>
<?php endif; ?>

