<?php
/** @var \Dotdigitalgroup\Email\Block\EmailCapture\EmailCaptureForNewsletter $block */
?>
<?php if ($block->isEasyEmailCaptureForNewsletterEnabled() || $block->isWebBehaviourTrackingEnabled()) : ?>
    <script type="text/x-magento-init">
    {
        "*": {
            "Dotdigitalgroup_Email/js/emailCapture":{
                "type":"newsletter",
                "url":"<?= $block->escapeHtml($block->getEmailCaptureUrl()); ?>",
                "enabled": "<?= $block->isEasyEmailCaptureForNewsletterEnabled(); ?>"
            }
        }
    }


    </script>
<?php endif; ?>
