<?php
/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Dotdigitalgroup\Email\Helper\Data $helper */
?>
<?php $helper = $this->helper(\Dotdigitalgroup\Email\Helper\Data::class); ?>

<script type="text/x-magento-init">
{
    "*": {
        "Dotdigitalgroup_Email/js/emailCapture":{
            "isEnabled":"<?= $block->escapeHtml($helper->isEasyEmailCaptureForNewsletterEnabled()); ?>",
            "type":"newsletter",
            "url":"<?= $block->escapeHtml($helper->getEmailCaptureUrl()); ?>"
        }
    }
}
</script>