<?php $helper = $this->helper('Dotdigitalgroup\Email\Helper\Data'); ?>

<?php if ($helper->isEasyEmailCaptureEnabled()) : ?>

    <script type="text/javascript">
        require(['jquery','domReady!'],function($){
            $("body").on("blur","input[id=customer-email]", function(){
                var email = $(this).val();
                if(email && validateEmail(email)){
                    $.post("<?php echo $block->escapeHtml($helper->getEmailCaptureUrl()); ?>", {email: email});
                }
            });
        });
        function validateEmail(sEmail) {
            var filter = /^([\w-\.]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([\w-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$/;
            if (filter.test(sEmail))
                return true;
            else
                return false;
        }
    </script>

<?php endif; ?>