<?php /** @var \Dotdigitalgroup\Email\Block\Roi $block */?>
<?php $isEnabled = $block->isRoiTrackingEnabled() ?>

<script type="text/x-magento-init">
    {
        "*": {
            "Dotdigitalgroup_Email/js/roiCode": {
                "isEnabled": "<?php echo (boolean) $isEnabled ?>",
                "total": "<?php echo $block->getTotal();?>",
                "items": <?php echo $block->getProductNames();?>
            }
        }
    }
</script>