<?php /** @var \Dotdigitalgroup\Email\Block\Roi $block */?>
<?php $isEnabled = $block->isRoiTrackingEnabled() ?>

<script type="text/x-magento-init">
    {
        "*": {
            "Dotdigitalgroup_Email/js/roiCode": {
                "isEnabled": "<?= $block->escapeHtml($isEnabled) ?>",
                "total": "<?= $block->escapeHtml($block->getTotal()); ?>",
                "items": <?= /* @noEscape */ $block->getProductNames(); ?>
            }
        }
    }
</script>