<?php
/** @var \Dotdigitalgroup\Email\Block\Tracking $block */
// phpcs:disable Magento2.Legacy.EscapeMethodsOnBlockClass
?>

<?php if ($block->isPageTrackingAvailable()): ?>
    <script type="text/x-magento-init">
        {
            "*": {
                "Dotdigitalgroup_Email/js/trackingCode": "<?= $block->escapeUrl($block->getPageTrackingUrl()) ?>"
            }
        }
    </script>
<?php endif;
// phpcs:enable
?>
