<?php
/** @var \Dotdigitalgroup\Email\Block\WebBehavior $block */
// phpcs:disable Magento2.Legacy.EscapeMethodsOnBlockClass
?>
<script type="text/x-magento-init">
    {
        "*": {
            "Dotdigitalgroup_Email/js/webBehaviorTracking": {
                "id": "<?= $block->escapeHtml($block->getProfileId()); ?>",
                "subdomain": "<?= $block->escapeHtml($block->getSubdomain()); ?>",
                "region": "<?= $block->escapeHtml($block->getRegionPrefix()); ?>"
            }
        }
    }
</script>
<?php // phpcs:enable ?>
