<div id="ddg-edc-preview">
    <div style="width: 200px; height: auto; float: right">
        <div align="center" style="font-weight: bold; padding: 3px; font-size: 12px;">
            PRODUCT STYLING PREVIEW
        </div>
        <div id="connector_configuration_dynamic_content_style_doc-preview"
             style="width: 200px; height: auto; border: solid 1px black; padding-top: 50px; padding-bottom: 50px;">
            <a href="<?php echo $block->getBaseUrl() ?>" title="Sample Image" target="_blank">
                <img src="<?php echo $block->getImagePlaceholder() ?>"
                     width="85" height="85" alt="Sample Image"
                     style="display: block; margin-left: auto; margin-right: auto; "/>
            </a>
            <div id="connector_configuration_dynamic_content_style_name-preview" align="center">
                Product Name
            </div>
            <div id="connector_configuration_dynamic_content_style_price-preview" align="center">
                <?php echo $block->getCurrencySymbol() . "99.99"; ?>
            </div>
            <div align="center">
                <a id="connector_configuration_dynamic_content_style_link-preview" target="_blank"
                   href="<?php echo $block->getBaseUrl(); ?>">View Now</a>
            </div>
        </div>
        <div align="center" style="margin-top: 20px; font-weight: bold; padding: 3px; font-size: 12px;">
            COUPON STYLING PREVIEW
        </div>
        <div id="connector_configuration_dynamic_content_style_coupon-preview" align="center"
             style="width: 200px; height: auto; border: solid 1px black; padding-top: 10px; padding-bottom: 10px;">
            DOT-XXX-XXX-XXX
        </div>
    </div>
</div>

<script>
    require([
        'jquery',
        'domReady!'
    ], function ($j) {
        var s = $j("#ddg-edc-preview");
        var pos = s.position();
        $j(window).scroll(function () {
            var windowpos = $j(window).scrollTop();
            if (windowpos >= pos.top &&
                windowpos
                    < ($j("#connector_configuration_dynamic_content_style_coupon_font_style").position().top - 350)) {
                s.attr("style", ""); //kill absolute positioning
                s.css({position: "fixed", top: "80px", left: $j(document).innerWidth() - 250});
            } else if (windowpos
                >= ($j("#connector_configuration_dynamic_content_style_coupon_font_style").position().top - 350)) {
                s.css({
                    position: "absolute",
                    top: (
                    $j("#connector_configuration_dynamic_content_style_coupon_font_style").position().top - 350) + "px",
                    left: $j(document).innerWidth() - 250
                });
            } else {
                s.css({
                    position: "absolute",
                    top: pos.top + "px",
                    left: $j(document).innerWidth() - 250
                });
            }
        });

        $j(window).resize(function () {
            $j("#ddg-edc-preview").css({left: $j(document).innerWidth() - 250});
        });

        var elementsA = [
            $j("#connector_configuration_dynamic_content_style_font_color"),
            $j("#connector_configuration_dynamic_content_style_font_size"),
            $j("#connector_configuration_dynamic_content_style_price_color"),
            $j("#connector_configuration_dynamic_content_style_price_font_size"),
            $j("#connector_configuration_dynamic_content_style_product_link_color"),
            $j("#connector_configuration_dynamic_content_style_product_link_font_size"),
            $j("#connector_configuration_dynamic_content_style_font"),
            $j("#connector_configuration_dynamic_content_style_color"),
            $j("#connector_configuration_dynamic_content_style_coupon_font_color"),
            $j("#connector_configuration_dynamic_content_style_coupon_font_size"),
            $j("#connector_configuration_dynamic_content_style_coupon_font_picker"),
            $j("#connector_configuration_dynamic_content_style_coupon_background_color")
        ];
        var elementsB = [
            $j("#connector_configuration_dynamic_content_style_font_style"),
            $j("#connector_configuration_dynamic_content_style_price_font_style"),
            $j("#connector_configuration_dynamic_content_style_product_link_style"),
            $j("#connector_configuration_dynamic_content_style_coupon_font_style")
        ];
        $j.each(elementsA, function (index, element) {
            var id = element.attr("id");
            var value = element.val();
            doYourThing(id, value);
            $j(element).on("change keyup blur input", function () {
                id = element.attr("id");
                value = element.val();
                doYourThing(id, value);
            });
        });
        $j.each(elementsB, function (index, element) {
            var id = element.attr("id");
            var value = element.val();
            doYourThing(id, value);
            $j(element).on("change", function () {
                id = element.attr("id");
                value = element.val();
                doYourThing(id, value);
            });
        });

        function doYourThing(id, value) {
            var link = $j("#" + "connector_configuration_dynamic_content_style_link-preview");
            var name = $j("#" + "connector_configuration_dynamic_content_style_name-preview");
            var doc = $j("#" + "connector_configuration_dynamic_content_style_doc-preview");
            var price = $j("#" + "connector_configuration_dynamic_content_style_price-preview");
            var coupon = $j("#" + "connector_configuration_dynamic_content_style_coupon-preview");
            switch (id) {
                case "connector_configuration_dynamic_content_style_font_color":
                    name.css("color", value);
                    break;
                case "connector_configuration_dynamic_content_style_font_size":
                    name.css("font-size", value);
                    break;
                case "connector_configuration_dynamic_content_style_font_style":
                    applyStyle(value, name);
                    break;
                case "connector_configuration_dynamic_content_style_price_color":
                    price.css("color", value);
                    break;
                case "connector_configuration_dynamic_content_style_price_font_size":
                    price.css("font-size", value);
                    break;
                case "connector_configuration_dynamic_content_style_price_font_style":
                    applyStyle(value, price);
                    break;
                case "connector_configuration_dynamic_content_style_product_link_color":
                    link.css("color", value);
                    break;
                case "connector_configuration_dynamic_content_style_product_link_font_size":
                    link.css("font-size", value);
                    break;
                case "connector_configuration_dynamic_content_style_product_link_style":
                    applyStyle(value, link);
                    break;
                case "connector_configuration_dynamic_content_style_font":
                    doc.css("font-family", value);
                    break;
                case "connector_configuration_dynamic_content_style_color":
                    doc.css("background-color", value);
                    break;
                case "connector_configuration_dynamic_content_style_coupon_font_color":
                    coupon.css("color", value);
                    break;
                case "connector_configuration_dynamic_content_style_coupon_font_size":
                    coupon.css("font-size", value);
                    break;
                case "connector_configuration_dynamic_content_style_coupon_font_picker":
                    coupon.css("font-family", value);
                    break;
                case "connector_configuration_dynamic_content_style_coupon_background_color":
                    coupon.css("background-color", value);
                    break;
                case "connector_configuration_dynamic_content_style_coupon_font_style":
                    applyStyle(value, coupon);
                    break;
            }
        }

        function applyStyle(styles, element) {
            element.css({"font-weight": "normal", "font-style": "normal", "text-decoration": "none"});
            $j.each(styles, function (index, style) {
                switch (style) {
                    case "nostyle":
                        element.css({"font-weight": "normal", "font-style": "normal", "text-decoration": "none"});
                        return false;
                        break;
                    case "bold":
                        element.css("font-weight", "bold");
                        break;
                    case "italic":
                        element.css("font-style", "italic");
                        break;
                    case "underline":
                        element.css("text-decoration", "underline");
                        break;
                }
            });
        }
    });
</script>