<?php $stats = $this->getStats(); ?>
<?php if(!empty($stats)): ?>
	<div class="entry-edit">
		<?php foreach($stats as $title => $campaignStat): ?>
			<div class="entry-edit">
				<div class="entry-edit-head" style="color: #fff;">
					<strong><?php echo __('Campaign Name: ') . __($title); ?></strong>
				</div>
				<fieldset>
					<table cellspacing="10" class="">
						<tbody>
						<?php foreach($campaignStat as $key => $value): ?>
							<tr>
								<td><strong><?php echo $this->__($key) ?></strong></td>
								<?php if($key == 'unsubscribed' or $key == 'softBounced' or $key == 'hardBounced'): ?>
									<?php
									if($value)
										$value = 'TRUE';
									else
										$value = 'FALSE';
									?>
									<td><?php echo $value ?></td>
								<?php elseif($key == 'dateSent' or $key == 'dateFirstOpened' or $key == 'dateLastOpened'): ?>
									<?php
									if($value == '1970-01-01T00:00:00Z')
										$value = '';
									?>
									<td>
										<?php
										if(!empty($value))
											echo new \Zend_Date($value, Zend_Date::ISO_8601)
										?>
									</td>
								<?php else: ?>
									<td><?php echo $value ?></td>
								<?php endif; ?>
							</tr>
						<?php endforeach; ?>
						</tbody>
					</table>
				</fieldset>
			</div>
		<?php endforeach; ?>
	</div>
<?php else: ?>
	<strong><?php echo "No activity found"; ?></strong>
<?php endif; ?>