<?php

namespace Dotdigitalgroup\Email\Plugin;

use Dotdigitalgroup\Email\Model\Coupon\CouponAttribute;
use Dotdigitalgroup\Email\Model\DateTimeFactory;
use Dotdigitalgroup\Email\Model\DateTimeZoneFactory;
use Magento\Framework\Stdlib\DateTime\TimezoneInterface;
use Magento\Framework\Api\SearchCriteriaBuilder;
use Magento\SalesRule\Api\CouponRepositoryInterface;
use Magento\SalesRule\Model\Coupon;
use Magento\SalesRule\Model\Utility;
use Magento\SalesRule\Model\Rule;
use Magento\Quote\Model\Quote\Address;

class CouponExpiredPlugin
{
    /**
     * Time of day a coupon remains valid until, in the store's own timezone.
     */
    private const END_OF_DAY = '23:59:59';

    /**
     * @var CouponRepositoryInterface
     */
    private $couponRepository;

    /**
     * @var SearchCriteriaBuilder
     */
    private $criteriaBuilder;

    /**
     * @var TimezoneInterface
     */
    private $timezone;

    /**
     * @var DateTimeFactory
     */
    private $dateTimeFactory;

    /**
     * @var DateTimeZoneFactory
     */
    private $dateTimeZoneFactory;

    /**
     * @param CouponRepositoryInterface $couponRepository
     * @param SearchCriteriaBuilder $criteriaBuilder
     * @param TimezoneInterface $timezone
     * @param DateTimeFactory $dateTimeFactory
     * @param DateTimeZoneFactory $dateTimeZoneFactory
     */
    public function __construct(
        CouponRepositoryInterface $couponRepository,
        SearchCriteriaBuilder $criteriaBuilder,
        TimezoneInterface $timezone,
        DateTimeFactory $dateTimeFactory,
        DateTimeZoneFactory $dateTimeZoneFactory
    ) {
        $this->couponRepository = $couponRepository;
        $this->criteriaBuilder = $criteriaBuilder;
        $this->timezone = $timezone;
        $this->dateTimeFactory = $dateTimeFactory;
        $this->dateTimeZoneFactory = $dateTimeZoneFactory;
    }

    /**
     * Check whether a coupon code was generated by Dotdigital, and if it has expired
     *
     * @param Utility $utility
     * @param bool $result
     * @param Rule $rule
     * @param Address $address
     * @return bool
     * @throws \Magento\Framework\Exception\LocalizedException
     */
    public function afterCanProcessRule(Utility $utility, bool $result, Rule $rule, Address $address)
    {
        if ($result
            && $rule->getCouponType() == Rule::COUPON_TYPE_SPECIFIC
            && (bool) $rule->getUseAutoGeneration()
            && !$rule->getToDate()
            && $couponCode = $address->getQuote()->getCouponCode()
        ) {
            $couponSearchResult = $this->couponRepository
                ->getList($this->criteriaBuilder->addFilter('code', $couponCode)->create())
                ->getItems();

            if (empty($couponSearchResult)) {
                return $result;
            }

            /** @var Coupon $coupon */
            $coupon = reset($couponSearchResult);
            if (!(bool) $coupon->getGeneratedByDotmailer()) {
                // not a dotdigital coupon
                return $result;
            }

            if ($ddgExtensionAttributes = $coupon->getExtensionAttributes()->getDdgExtensionAttributes()) {
                /** @var CouponAttribute $ddgExtensionAttributes */
                if ($this->isExpired($ddgExtensionAttributes)) {
                    // individual coupon has expired
                    $rule->setIsValidForAddress($address, false);
                    return false;
                }
            }
        }

        return $result;
    }

    /**
     * Check whether a coupon's expiry has passed.
     *
     * Bulk coupon expiry dates are stored at 23:59:59 and treated as floating calendar dates in
     * the current store's timezone. EDC coupon expiries retain their exact stored UTC timestamp.
     *
     * @param CouponAttribute $couponAttribute
     * @return bool
     */
    private function isExpired(CouponAttribute $couponAttribute): bool
    {
        $expiresAt = $couponAttribute->getExpiresAt();
        if (empty($expiresAt)) {
            return false;
        }

        try {
            $expiresAtDate = $couponAttribute->getExpiresAtDate();
        } catch (\Exception $e) {
            return false;
        }

        if (!$expiresAtDate || $expiresAtDate->format('Y-m-d H:i:s') !== $expiresAt) {
            return false;
        }

        if ($expiresAtDate->format('H:i:s') !== self::END_OF_DAY) {
            return $this->timezone->date($expiresAtDate) < $this->timezone->date();
        }

        $storeTimezone = $this->dateTimeZoneFactory->create([
            'timezone' => $this->timezone->getConfigTimezone()
        ]);

        $expiresAtDate = $this->dateTimeFactory->create([
            'time' => sprintf('%s %s', $expiresAtDate->format('Y-m-d'), self::END_OF_DAY),
            'timezone' => $storeTimezone
        ]);

        return $expiresAtDate < $this->timezone->date();
    }
}
