<div class="actions actions-create-addressbook">
	<div id="validation_result" class="message-validation hidden"></div>
	<button class="action-create-addressbook" type="button" id="<?php echo $block->getHtmlId() ?>">
		<span><?php echo $block->escapeHtml(__($block->getButtonLabel())) ?></span>
	</button>
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "Dotdigitalgroup_Email/js/addressBook":{
                "url":"<?php echo $block->escapeUrl($block->getAjaxUrl()) ?>"
            }
        }
    }
</script>