<?php /** @var \Dotdigitalgroup\Email\Block\Adminhtml\Config\Createdatafield $block */?>
<div class="actions actions-create-datafield">
    <div id="validation_result" class="message-validation hidden"></div>
    <button class="action-create-datafield" type="button" id="<?php echo $block->getHtmlId() ?>">
        <span><?php echo $block->escapeHtml(__($block->getButtonLabel())) ?></span>
    </button>
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "Dotdigitalgroup_Email/js/dataFields":{
                "url":"<?php echo $block->escapeUrl($block->getAjaxUrl()) ?>"
            }
        }
    }
</script>