<table class="message-system-short">
    <tr>
        <th>
            <strong class="message-system-short-label">
                <?php /* @escapeNotVerified */ echo __('API valid')?>:
            </strong>
        </th>
        <td><?php echo /* @escapeNotVerified */ $block->getApiValid() ?></td>
    </tr>
    <tr>
        <th>
            <strong class="message-system-short-label">
                <?php /* @escapeNotVerified */ echo __('Cron last execution')?>:
            </strong>
        </th>
        <td><?php echo /* @escapeNotVerified */ $block->getCronLastExecution(); ?></td>
    </tr>
    <tr>
        <th>
            <strong class="message-system-short-label">
                <?php /* @escapeNotVerified */ echo __('Dynamic content passcode')?>:
            </strong>
        </th>
        <td><?php echo $block->escapeHtml($block->getDynamicContentPasscode())?></td>
    </tr>
    <tr>
        <th>
            <strong class="message-system-short-label">
                <?php /* @escapeNotVerified */ echo __('Abandoned Cart limit time')?>:
            </strong>
        </th>
        <td><?php /* @escapeNotVerified */ echo $block->getAbandonedCartLimit()?></td>
    </tr>
</table>
    

