<?php /** @var \Dotdigitalgroup\Email\Block\Adminhtml\Dashboard\Information $block */?>
<table class="message-system-short">
    <tr>
        <th>
            <strong class="message-system-short-label">
                <?= $block->escapeHtml(__('API valid')) ?>:
            </strong>
        </th>
        <td><?= /* @noEscape */ $block->getApiValid() ?></td>
    </tr>
    <tr>
        <th>
            <strong class="message-system-short-label">
                <?= $block->escapeHtml(__('Cron last execution')) ?>:
            </strong>
        </th>
        <td><?= /* @noEscape */ $block->getCronLastExecution(); ?></td>
    </tr>
    <tr>
        <th>
            <strong class="message-system-short-label">
                <?= $block->escapeHtml(__('Dynamic content passcode')) ?>:
            </strong>
        </th>
        <td><?= $block->escapeHtml($block->getDynamicContentPasscode()) ?></td>
    </tr>
    <tr>
        <th>
            <strong class="message-system-short-label">
                <?= $block->escapeHtml(__('Abandoned Cart limit time')) ?>:
            </strong>
        </th>
        <td><?= $block->escapeHtml($block->getAbandonedCartLimit()) ?></td>
    </tr>
</table>
    

