<?php /** @var \Dotdigitalgroup\Email\Block\Adminhtml\Dashboard\Information $block */?>
<table class="message-system-short">
    <tr>
        <th>
            <strong class="message-system-short-label">
                <?= $block->escapeHtml(__('PHP Version')) ?>:
            </strong>
        </th>
        <td><div class="message-link"><?= $block->escapeHtml($block->getPhpVersion()) ?></div></td>
    </tr>
    <tr>
        <th>
            <strong class="message-system-short-label">
                <?= $block->escapeHtml(__('PHP max execution time')) ?>:
            </strong>
        </th>
        <td><?= $block->escapeHtml($block->getPhpMaxExecutionTime()); ?></td>
    </tr>
    <tr>
        <th>
            <strong class="message-system-short-label">
                <?= $block->escapeHtml(__('Mode ')) ?>:
            </strong>
        </th>
        <td><?= $block->escapeHtml($block->getDeveloperMode()) ?></td>
    </tr>
    <tr>
        <th>
            <strong class="message-system-short-label">
                <?= $block->escapeHtml(__('Magento Version ')) ?>:
            </strong>
        </th>
        <td><?= $block->escapeHtml($block->getMagentoVersion()) ?></td>
    </tr>
    <tr>
        <th>
            <strong class="message-system-short-label">
                <?= $block->escapeHtml(__('Connector Version ')) ?>:
            </strong>
        </th>
        <td><?= $block->escapeHtml($block->getConnectorVersion()) ?></td>
    </tr>

</table>
    
