<table class="message-system-short">
    <tr>
        <th>
            <strong class="message-system-short-label">
                <?php /* @noEscape */ echo __('PHP Version')?>:
            </strong>
        </th>
        <td><div class="message-link"><?php echo $block->escapeHtml($this->getPhpVersion()) ?></td></div>
    </tr>
    <tr>
        <th>
            <strong class="message-system-short-label">
                <?php /* @noEscape */ echo __('PHP max execution time')?>:
            </strong>
        </th>
        <td><?php /* @noEscape */ echo $block->getPhpMaxExecutionTime(); ?></td>
    </tr>
    <tr>
        <th>
            <strong class="message-system-short-label">
                <?php /* @noEscape */ echo __('Mode ')?>:
            </strong>
        </th>
        <td><?php /* @noEscape */ echo $block->getDeveloperMode()?></td>
    </tr>
    <tr>
        <th>
            <strong class="message-system-short-label">
                <?php /* @noEscape */ echo __('Magento Version ')?>:
            </strong>
        </th>
        <td><?php echo $block->escapeHtml($block->getMagentoVersion()  .  '  ' . $block->getMagentoEdition())?></td>
    </tr>
    <tr>
        <th>
            <strong class="message-system-short-label">
                <?php /* @noEscape */ echo __('Connector Version ')?>:
            </strong>
        </th>
        <td><?php echo $block->escapeHtml($block->getConnectorVersion()) ?></td>
    </tr>

</table>
    
