<?php /** @var \Dotdigitalgroup\Email\Block\Adminhtml\Dashboard\Information $block */?>
<table>
    <tr>
        <th>
            <strong class="message-system-short-label">
                <?= $block->escapeHtml(__('PHP version')) ?>:
            </strong>
        </th>
        <td><div class="message-link"><?= $block->escapeHtml($block->getPhpVersion()) ?></div></td>
    </tr>
    <tr>
        <th>
            <strong class="message-system-short-label">
                <?= $block->escapeHtml(__('PHP max execution time')) ?>:
            </strong>
        </th>
        <td><?= $block->escapeHtml($block->getPhpMaxExecutionTime()); ?></td>
    </tr>
    <tr>
        <th>
            <strong class="message-system-short-label">
                <?= $block->escapeHtml(__('Mode')) ?>:
            </strong>
        </th>
        <td><?= $block->escapeHtml($block->getDeveloperMode()) ?></td>
    </tr>
    <tr>
        <th>
            <strong class="message-system-short-label">
                <?= $block->escapeHtml(__('Magento version')) ?>:
            </strong>
        </th>
        <td><?= $block->escapeHtml($block->getMagentoVersion()) ?></td>
    </tr>
    <?php foreach ($block->fetchActiveModules() as $module): ?>
        <tr>
            <th>
                <strong class="message-system-short-label">
                    <?= $block->escapeHtml(__($module['name'])) ?>:
                </strong>
            </th>
            <td><?= $block->escapeHtml(__('v. %1', $module['version'])) ?></td>
        </tr>
    <?php endforeach; ?>
</table>
