<?php
/** @var \Dotdigitalgroup\Email\Block\Adminhtml\Dashboard $block */
// phpcs:disable Magento2.Legacy.EscapeMethodsOnBlockClass
?>
<div class="content-header">
    <?= $block->getChildHtml('adminhtml.system.config.switcher');?>
</div>
<div class="message-system">
    <?= $block->getChildHtml('store_language');?>
    <div class="message-system-inner add-top-border">
        <div class="ddg-dashboard-container">
            <table cellspacing="25" class="ddg-dashboard-table">
                <tr>
                    <td class="ddg-dashboard-cell">
                        <?= $block->getChildHtml('dotdigitalgroup.email.dashboard_left') ?>
                    </td>
                    <td class="ddg-dashboard-cell">
                        <?= $block->getChildHtml('dotdigitalgroup.email.dashboard_right') ?>
                    </td>
                </tr>
            </table>
        </div>
    </div>
</div>

<?php // phpcs:enable ?>
