<?php /** @var \Dotdigitalgroup\Email\Block\Adminhtml\Dashboard $block */?>
<div class="content-header">
    <?= $block->getChildHtml('adminhtml.system.config.switcher');?>
</div>
<div class="dashboard-container">
    <?= $block->getChildHtml('store_language');?>
    <table cellspacing="25" class="message-system-inner ddg-dashboard-table">
        <tr>
            <td><?= $block->getChildHtml('dotdigitalgroup.email.dashboard_left') ?></td>
            <td><?= $block->getChildHtml('dotdigitalgroup.email.dashboard_right') ?></td>
        </tr>
    </table>
    <table>
        <tr>
            <td><?= $block->getChildHtml('dotdigitalgroup.email.dashboard_config') ?></td>
        </tr>
    </table>
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "Dotdigitalgroup_Email/js/dashboard":{
                "contactLink":"<?= $block->escapeUrl($block->getContactSyncLink()); ?>",
                "importerLink":"<?= $block->escapeUrl($block->getImporterLink()); ?>"
            }
        }
    }
</script>