<?php
/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Dotdigitalgroup\Email\Helper\Data $helper */
?>
<?php $helper = $this->helper('Dotdigitalgroup\Email\Helper\Data'); ?>

<script type="text/x-magento-init">
    {
        "*": {
            "Dotdigitalgroup_Email/js/initMailcheck":{
                "isEnabled":"<?= $block->escapeHtml($helper->isMailCheckEnabledForCurrentStore()); ?>"
            }
        }
    }
</script>