<?php
/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Dotdigitalgroup\Email\Helper\Data $helper */
?>
<?php $helper = $this->helper(\Dotdigitalgroup\Email\Helper\Data::class); ?>

<script type="text/x-magento-init">
    {
        "*": {
            "Dotdigitalgroup_Email/js/initMailcheck":{
                "isEnabled":"<?php echo $block->escapeHtml($helper->isMailCheckEnabledForCurrentStore()); ?>"
            }
        }
    }
</script>