<?php

declare(strict_types=1);

use Magento\Framework\Escaper;
use Dotdigitalgroup\Email\ViewModel\DotdigitalEmailCaptureView;
use Magento\Framework\View\Element\Template;

/**
 * @var Escaper $escaper
 * @var DotdigitalEmailCaptureView $viewModel
 * @var Template $block
 */
$viewModel = $block->getData('view_model');

?>
<?= /** @noEscape */ $viewModel->renderConfig() ?>
<?= /** @noEscape */ $viewModel->renderScript() ?>
