<?php

declare(strict_types=1);

use Magento\Framework\Escaper;
use Dotdigitalgroup\Email\ViewModel\DotdigitalTagView;
use Magento\Framework\View\Element\Template;

/**
 * @var Escaper $escaper
 * @var Template $block
 * @var DotdigitalTagView $viewModel
 */
$viewModel = $block->getData('view_model');
?>
<?= /** @noEscape */ $viewModel->renderTag(); ?>
<?= /** @noEscape */ $viewModel->renderScript(); ?>
<?= /** @noEscape */ $viewModel->trackPageVisit(); ?>

