<div class="switcher">
    <label style="font-weight: bold; padding-right: 10px;" for="connector-log-selector">Select Log File:</label>
    <select id="connector-log-selector" style="width: 20em">
        <option value="connector">Marketing Automation Log</option>
        <option value="system">Magento System Log</option>
        <option value="exception">Magento Exception Log</option>
        <option value="debug">Magento Debug Log</option>
    </select>
    <button id="connector-log-reloader" style="margin-left: 5px;">
        <span>Reload</span>
    </button>
</div>
<div style="padding-top: 25px;">
    <h3 id="connector-log-header" style="border-bottom: 4px solid #dfdfdf; color: #eb5e00;">
        Marketing Automation Log
    </h3>
</div>

<div style="border: 4px solid #dfdfdf; overflow: hidden; height: 510px; padding: 5px;">
    <div id="log_data"
         style="width:100%;height:500px;overflow:auto;margin:0px;padding:3px;background:black;color:#2EC029;
         font:normal 11px Lucida Console, Courier New, serif;">
        <?php echo $block->getLogFileContent(); ?>
    </div>
</div>

<script type="text/javascript">
    require([
        'prototype'
    ], function () {
        console_scroll();
        function console_scroll() {
            dh = $("log_data").scrollHeight
            ch = $("log_data").clientHeight
            if (dh > ch) {
                moveme = dh - ch
                $("log_data").scrollTop = moveme;
            }
        }

        //Observer select
        $('connector-log-selector').observe('change', function (event) {
            doUpdate($('connector-log-selector').getValue());
        });
        //Observe button click for reload
        $('connector-log-reloader').observe('click', function (event) {
            doUpdate($('connector-log-selector').getValue());
        });
        function doUpdate(log) {
            var url = '<?php echo $block->getUrl('dotdigitalgroup_email/connector/ajaxlogcontent') ?>';
            new Ajax.Request(url,
                {
                    method: 'post',
                    parameters: {
                        log: log
                    },
                    onSuccess: function (transport) {
                        var json = transport.responseJSON;
                        $('log_data').update(json.content);
                        $('connector-log-header').update(json.header);
                        console_scroll();
                    }
                });
        }
    });
</script>