<?php
/** @var \Magento\Backend\Block\Template $block */
?>
<script type="text/x-magento-init">
    {
        "*": {
            "Dotdigitalgroup_Email/js/rulesDatafields":{
                "ajaxUrl":"<?= $block->escapeUrl(
                    $block->getUrl('dotdigitalgroup_email/rules/ajax')
                ); ?>",
                "selectAjaxUrl":"<?= $block->escapeUrl(
                    $block->getUrl('dotdigitalgroup_email/rules/selected')
                ); ?>",
                "valueAjaxUrl":"<?= $block->escapeUrl(
                    $block->getUrl('dotdigitalgroup_email/rules/value')
                ); ?>"
            }
        }
    }
</script>
