<?php
/** @var \Magento\Backend\Block\Template $block */
// @codingStandardsIgnoreFile
?>
<script type="text/x-magento-init">
    {
        "*": {
            "Dotdigitalgroup_Email/js/rulesDatafields":{
                "ajaxUrl":"<?php echo $block->escapeUrl(
                    $block->getUrl('dotdigitalgroup_email/rules/ajax')
                ); ?>",
                "selectAjaxUrl":"<?php echo $block->escapeUrl(
                    $block->getUrl('dotdigitalgroup_email/rules/selected')
                ); ?>",
                "valueAjaxUrl":"<?php echo $block->escapeUrl(
                    $block->getUrl('dotdigitalgroup_email/rules/value')
                ); ?>"
            }
        }
    }
</script>