<?php
/**
 * @var $block \Magento\Framework\View\Element\Template
 * @var $escaper \Magento\Framework\Escaper
 * @var $view \Dotdigitalgroup\Email\ViewModel\Customer\Account\AddressBooks
 */
// phpcs:disable Magento2.Legacy.EscapeMethodsOnBlockClass

$view = $block->getData('config');
?>

<?php
$additionalBooks = $view->getAdditionalBooksToShow();

if (!empty($additionalBooks)): ?>
    <fieldset class="fieldset">
        <legend class="legend">
            <span><?= $block->escapeHtml(__('Lists')) ?></span>
        </legend>
        <?php foreach ($additionalBooks as $books): ?>
            <div class="control field choice" >
                <input type="checkbox" name="additional_subscriptions[]"
                       id="<?= $block->escapeHtml($books["name"]); ?>"
                       value="<?= $block->escapeHtml($books["value"]) ?>"
                       title="<?= $block->escapeHtml($books["name"]) ?>"
                    <?php if ($books["subscribed"]): ?>
                        checked="checked"
                    <?php endif; ?> class="checkbox"
                />
                <label for="<?= $block->escapeHtml($books["name"]); ?>">
                    <?= $block->escapeHtml($books["name"]) ?>
                </label>
            </div>
        <?php endforeach; ?>
    </fieldset>
<?php endif;
// phpcs:enable
?>
