<?php
/**
 * @var $block \Magento\Framework\View\Element\Template
 * @var $escaper \Magento\Framework\Escaper
 * @var $view \Dotdigitalgroup\Email\ViewModel\Customer\Account\DataFields
 */

// @codingStandardsIgnoreFile
$view = $block->getData('config');
?>

<?php
$dataFields = $view->getDataFieldsToShow();
$dataFieldHtmlProperties = [
    'Numeric' => [
        'input_type' => 'number',
        'class' => 'form-input'
    ],
    'Date' => [
        'input_type' => 'date',
        'class' => 'form-input date-field'
    ],
    'String' => [
        'input_type' => 'text',
        'class' => 'input-text form-input'
    ]
];

if (!empty($dataFields)): ?>
    <fieldset class="fieldset">
        <legend class="legend">
            <span><?= $block->escapeHtml(__('Information')) ?></span>
        </legend>
            <?php foreach ($dataFields as $dataField): ?>
                <div class="field">
                    <label for="<?= $block->escapeHtml($dataField['name']) ?>">
                        <?= $block->escapeHtml($dataField['name']) ?>
                    </label>
                    <?php if ($dataField['type'] == "Boolean"): ?>
                        <div class="control">
                            <select class="form-select"
                                    name="data_fields[<?= $block->escapeHtml($dataField['name']) ?>]"
                                    id="<?= $block->escapeHtml($dataField['name']) ?>"
                                    title="<?= $block->escapeHtml($dataField['name']) ?>">
                                <?php //@codingStandardsIgnoreStart ?>
                                <option value="1"<?php if ($block->escapeHtml($dataField['value'])): ?>
                                    selected="selected"<?php endif; ?>><?= __('Yes') ?></option>
                                <option value="0"<?php if (!$block->escapeHtml($dataField['value'])): ?>
                                    selected="selected"<?php endif; ?>><?= __('No') ?></option>
                                <?php //@codingStandardsIgnoreEnd ?>
                            </select>
                        </div>
                    <?php else: ?>
                        <div class="input-box">
                            <input type="<?= $dataFieldHtmlProperties[$dataField['type']]['input_type']; ?>"
                                   class="<?= $dataFieldHtmlProperties[$dataField['type']]['class']; ?>"
                                   title="<?= $block->escapeHtml($dataField['name']) ?>"
                                   value="<?= $block->escapeHtml($dataField['value']) ?>"
                                   name="data_fields[<?= $block->escapeHtml($dataField['name']) ?>]"
                                   id="<?= $block->escapeHtml($dataField['name']) ?>"
                            />
                        </div>
                    <?php endif; ?>
                </div>
        <?php endforeach; ?>
    </fieldset>
<?php endif; ?>
