<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $this->getLang() ?>" lang="<?php echo $this->getLang() ?>">
<head>
</head>
<body>
<div class="main-container col1-layout">
    <div class="main">
        <div class="col-main">
	        <h1>blank template</h1>
            <?php echo $this->getChildHtml('content') ?>
        </div>
    </div>
</div>
</body>
</html>
